{
 "title": "Error budget TEST",
 "description": "Tracks service's SLO and error budget consumption.",
 "tags": [
  "error_budget",
  "SLO"
 ],
 "time": { "from": "now/M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "service_slo_target", "query": "99.2" },
   { "name": "error_budget", "query": "0.008" },
   { "name": "operation_day_start", "query": "4" },
   { "name": "operation_day_end", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operation day start (MSK)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$operation_day_start" }
   ]
  },
  {
   "title": "General error budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(order_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < ($operation_day_start))\r\n)) / (days_in_month() * 24* 60 * 60)"
    }
   ]
  },
  {
   "title": "General error budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\ndays_in_month() * 24 * ($error_budget) -\r\n(running_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(order_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < ($operation_day_start))\r\n)) /60 / 60\r\n"
    }
   ]
  },
  {
   "title": "Client scenario budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(smkt_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)"
    }
   ]
  },
  {
   "title": "Client scenario budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\ndays_in_month() * 24 * ($error_budget) -\r\n(running_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(order_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < ($operation_day_start))\r\n)) /60 / 60\r\n"
    }
   ]
  },
  {
   "title": "Operation day end (MSK)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$operation_day_end" }
   ]
  },
  {
   "title": "Fulfillment budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(order_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < ($operation_day_start))\r\n)) / (days_in_month() * 24* 60 * 60)"
    }
   ]
  },
  {
   "title": "Fulfillment budget left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\ndays_in_month() * 24 * ($error_budget) -\r\n(running_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(order_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < ($operation_day_start))\r\n)) /60 / 60\r\n"
    }
   ]
  },
  {
   "title": "Target SLO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$service_slo_target" }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "days_in_month() * 24 * ($error_budget)"
    }
   ]
  },
  {
   "title": "Burn rate 12h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "Burn rate 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "Burn rate 1 week",
   "type": "stat",
   "description": "Если burn rate за неделю более 0.25% - значит есть риск не попасть в целевой бюджет ошибок за месяц",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "1 week Prediction",
   "type": "stat",
   "description": "Пытаемся предсказать % оставшегося бюджета через неделю на основании предыдущих данных",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(smkt_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)"
    }
   ]
  },
  {
   "title": "General error budget",
   "type": "timeseries",
   "description": "Совокупный по входным точкам и бизнес процессам бюджет ошибок, с учетом времени работы сервиса (04:00-00:00). \nЕсли мы расходуем бюджет значит пользователь либо не может войти в приложение или оно долго открывается, либо не может пройти основной сценарий заказа или в процессе его прохождения пользователь получает большие отклики.\nСчитается только уникальное время недоступности, то есть недоступность нескольких сущностей не будет расходовать бюджет сильнее чем только одной из них.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(smkt_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left"
    }
   ]
  },
  {
   "title": "Client scenario budget",
   "type": "timeseries",
   "description": "Совокупный по входным точкам и бизнес процессам бюджет ошибок, с учетом времени работы сервиса (04:00-00:00). \nЕсли мы расходуем бюджет значит пользователь либо не может войти в приложение или оно долго открывается, либо не может пройти основной сценарий заказа или в процессе его прохождения пользователь получает большие отклики.\nСчитается только уникальное время недоступности, то есть недоступность нескольких сущностей не будет расходовать бюджет сильнее чем только одной из них.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(smkt_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left"
    }
   ]
  },
  {
   "title": "Fulfillment budget",
   "type": "timeseries",
   "description": "Совокупный по входным точкам и бизнес процессам бюджет ошибок, с учетом времени работы сервиса (04:00-00:00). \nЕсли мы расходуем бюджет значит пользователь либо не может войти в приложение или оно долго открывается, либо не может пройти основной сценарий заказа или в процессе его прохождения пользователь получает большие отклики.\nСчитается только уникальное время недоступности, то есть недоступность нескольких сущностей не будет расходовать бюджет сильнее чем только одной из них.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100,\r\n    order_web_errors = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) default\r\n    duration_over_time(smkt_web_errors[:15s],16s)) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left"
    }
   ]
  },
  {
   "title": "Product error budget",
   "type": "timeseries",
   "description": "Бюджет ошибок по продуктам, с учетом времени работы сервиса (04:00-00:00). \nЕсли мы расходуем бюджет значит пользователь либо не может войти в приложение или оно долго открывается, либо не может пройти основной сценарий заказа или в процессе его прохождения пользователь получает большие отклики.\nСчитается только уникальное время недоступности, то есть недоступность нескольких сущностей не будет расходовать бюджет сильнее чем только одной из них.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) ) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left - product 1"
    },
    {
     "expr": "WITH(\r\n    order = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(order[:15s],16s) ) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left - product 2"
    }
   ]
  },
  { "title": "Budget per product", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "product 1 error budget ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    catalog_auth_responses = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(catalog_auth_responses[:15s],16s) ) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left"
    }
   ]
  },
  {
   "title": "product 2  Burn rate 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "product 2  Burn rate 1 week",
   "type": "stat",
   "description": "Если burn rate за неделю более 0.25% - значит есть риск не попасть в целевой бюджет ошибок за месяц",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "product 2  error budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(\r\n    order = 100 * (1 - exp(-200 * rand())) < 100\r\n)\r\n\r\n((days_in_month() * 24* 60 * 60) -\r\nrunning_sum(\r\n    (duration_over_time(order[:15s],16s) ) or vector (0) ifnot (hour(time()[1h:1h] + timezone_offset(\"Europe/Moscow\")[1h:1h])[1h:1h] < (3))\r\n)) / (days_in_month() * 24* 60 * 60)",
     "legendFormat": "Budget left"
    }
   ]
  },
  {
   "title": "product 2  Burn rate 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  },
  {
   "title": "product 2 Burn rate 1 week",
   "type": "stat",
   "description": "Если burn rate за неделю более 0.25% - значит есть риск не попасть в целевой бюджет ошибок за месяц",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$A", "type": "math" }
   ]
  }
 ]
}